[problem]
title = "Electron Two-stream Instability"
description = """
"""

[[species]]
name = "species 1"
angle_frequency = 0.707100 # Hz
charge_to_mass_ratio = -1.0
parallel_velocity = 1.0
perpendicular_velocity = 0.0
drift_velocity = -3.0

[[species]]
name = "species 2"
angle_frequency = 0.707100 # Hz
charge_to_mass_ratio = -1.0
parallel_velocity = 1.0
perpendicular_velocity = 0.0
drift_velocity = 3.0
